//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Sfx
    {
        public const string BundleName = "sfx";
        public const string ABILITYLEVELUP = "AbilityLevelUp";
        public const string BALL = "Ball";
        public const string BOMB = "bomb";
        public const string COIN = "Coin";
        public const string DIE = "Die";
        public const string ENEMYDIE = "EnemyDie";
        public const string EXP = "Exp";
        public const string GAME_PASS = "Game_pass";
        public const string GETALLEXP = "GetAllExp";
        public const string HIT = "Hit";
        public const string HP = "Hp";
        public const string HURT = "Hurt";
        public const string KNIFE = "Knife";
        public const string LEVEL_UP = "Level_up";
    }
    public class Testuigamestartpanel_prefab
    {
        public const string BundleName = "testuigamestartpanel_prefab";
        public const string TESTUIGAMESTARTPANEL = "TestUIGameStartPanel";
    }
    public class Uigameoverpanel_prefab
    {
        public const string BundleName = "uigameoverpanel_prefab";
        public const string UIGAMEOVERPANEL = "UIGameOverPanel";
    }
    public class Uigamepanel_prefab
    {
        public const string BundleName = "uigamepanel_prefab";
        public const string UIGAMEPANEL = "UIGamePanel";
    }
    public class Uigamepasspanel_prefab
    {
        public const string BundleName = "uigamepasspanel_prefab";
        public const string UIGAMEPASSPANEL = "UIGamePassPanel";
    }
}
